default_environment: dev
project_id: 019eaf06-7256-77f1-a538-7cb8ba8b83ba
environments:
- name: dev
- name: staging
- name: prod
python: python3.11
plugins:
  extractors:
  - name: tap-postgres
    variant: meltanolabs
    pip_url: meltanolabs-tap-postgres
    config:
      database: postgres
      filter_schemas:
      - public
      host: aws-1-ap-northeast-1.pooler.supabase.com
      port: 5432
      user: postgres.dharviqgzniphshjrgey
    select:
    - '*.*'
  loaders:
  - name: target-bigquery
    variant: z3z1ma
    pip_url: git+https://github.com/z3z1ma/target-bigquery.git setuptools<80
    config:
      batch_size: 100000
      credentials_path: /home/angjennfang/sctp-team2-project2-elt-ROTATED-dbcb3cd092f4.json
      dataset: brazil_ecommerce_raw_JF
      denormalized: true
      flattening_enabled: true
      flattening_max_depth: 1
      method: batch_job
      project: sctp-team2-project2-elt
